@startuml
class TodoList extends Application{
    + start(stage: Stage);
    + main();
}

class GuiController implements Initialize{
    + getEvents(): Object[];
    + initialize(arg0: URL, arg1: ResourceBundle);
    + comboChanged();
    + saveFile(file: File);
    + openFile(file: File);

    - deleteSelectedEvent();
    - deleteAllEvents();
    - editEvent();
    - displayCompletedTasks();
    - displayNonCompletedTasks();
    - displayAllTasks();
    - addEvent();
    - refresh();
    - markComplete();
    - markIncomplete();
}

class LocalEvent{
    - date: LocalDate;
    - description: String;
    - completed: boolean;

    + LocalEvent(date: LocalDate, description: String);

    + getDate(): date;
    + setDate(date: LocalDate);
    + getDescription(): description;
    + setDescription(description: String);
    + toString(): String;
    + getCompleted(): boolean;
    + setCompleted(completed: boolean);
}
@enduml